export const CHANGE_INPUT_VALUE = 'change_input_value'
export const CHANGE_LIST_VALUE = 'change_list_value'
export const CHANGE_DELETE_VALUE = 'change_delete_value'
export const GET_AJAX_VALUE = 'get_ajax_value'
export const GET_INIT_LIST = 'get_init_list'